IMAGE_NAME = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = "Grafana-SRV02"
  end

  config.vm.box = IMAGE_NAME
  config.vm.box_version = "20240821.0.1"
  config.vm.network "private_network", type: 'dhcp', virtualbox__intnet: 'VirtualNetwork'

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
  SHELL

end