IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = "Bastion-SRV03"
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
  ubuntu.vm.network "forwarded_port", guest: 80, host: 8002, host_ip: "127.0.0.1"
    ubuntu.vm.network "private_network", ip: "192.168.1.5", virtualbox__intnet: "intnet"
    ubuntu.vm.hostname = "bastion"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
  SHELL
  
end